name: CI

on:
  push:
    branches: [main, develop, feat/*]
  pull_request:
    branches: [main, develop]
    types: [opened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    strategy:
      matrix:
        node-version: [22.x]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9
      
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Run lint
        run: pnpm lint
      
      - name: Run type check
        run: pnpm check-types
      
      - name: Build packages
        run: pnpm build
      
      - name: Install Playwright browsers
        run: cd packages/ui && npx playwright install --with-deps chromium
      
      - name: Build Storybook
        run: pnpm build-storybook
      
      - name: Run Storybook tests
        run: pnpm test:storybook:ci
      
      - name: Upload test results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: packages/ui/test-results/
          retention-days: 7